### ISSUE TITLE
speed up data correction

### ISSUE THREAD

**Issue by jiang-jingjing** [jiang-jingjing/PioneerImageReconstruction#1]
replaced codes:
[[timing_data_correction_z3.m](https://github.com/jiang-jingjing/PioneerImageReconstruction/blob/master/timing_data_correction_z3.m](https://github.com/jiang-jingjing/PioneerImageReconstruction/blob/master/timing_data_correction_z3.m))

[Piccolo_data_correction](https://github.com/jiang-jingjing/PioneerImageReconstruction/tree/master/Piccolo_data_correction)

**Comment by gitstratos** [comment]
First version that use the parfor from Matlab is online. Let me know in case of issues.
I will try other types of improvements as a next step.

**Comment by jiang-jingjing** [comment]
the improvement has been tested
